source 'https://github.com/CocoaPods/Specs.git'

target 'SPXCoreData', :exclusive => true do
  pod "SPXCoreData", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SPXCoreData", :path => "../"

  pod 'Kiwi'
end
